### ISSUE TITLE
out of resources error with a 10s runtime, not with 1s; or larger ensembles.

### ISSUE THREAD

**Issue by adityagilra** [nengo/nengo_ocl#119]
Hi,

First thanks for the huge effort going into nengo and nengo_ocl.

I'm running nengo_ocl github dev version (python setup.py develop --user) with nengo 2.2.0 (sudo pip install nengo).
[To get nengo_ocl installed I needed to remove the --addopts and --pyargs nengo line from setup.py else I'd get an error unknown option --add-opts.]

I'm able to run the example scripts:
benchmark_circconv.py and profile_circconv.py
albeit with a warning that 2.2.0 may not work, since 2.1.2 is officially supported. So am unsure if the following issue is just due to this or some other reason?

`python benchmark_circconv.py ocl 10`
works fine.

But
`python benchmark_circconv.py ocl 100`
gives the error:

```
  File "benchmark_circconv.py", line 83, in <module>
    sim.run(simtime)
  File "/usr/local/lib/python2.7/dist-packages/nengo/simulator.py", line 261, in run
    self.run_steps(steps, progress_bar=progress_bar)
  File "/home/aditya/nengo_ocl/nengo_ocl/simulator.py", line 945, in run_steps
    self._plans.call_n_times(B)
  File "/home/aditya/nengo_ocl/nengo_ocl/plan.py", line 125, in call_n_times
    last_event = self.enqueue_n_times(n)
  File "/home/aditya/nengo_ocl/nengo_ocl/plan.py", line 138, in enqueue_n_times
    last_event = plan.enqueue(profiling=self.profiling)
  File "/home/aditya/nengo_ocl/nengo_ocl/plan.py", line 92, in enqueue
    wait_for=wait_for)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl/cffi_cl.py", line 1229, in enqueue_nd_range_kernel
    global_work_size, local_work_size, c_wait_for, num_wait_for))
  File "/usr/local/lib/python2.7/dist-packages/pyopencl/cffi_cl.py", line 561, in _handle_error
    raise e
pyopencl.cffi_cl.RuntimeError: clenqueuendrangekernel failed: OUT_OF_RESOURCES
```

Similarly with other scripts. For the learn channel example from:
https://pythonhosted.org/nengo/examples/learn_communication_channel.html
1s of simulation works fine with nengo_ocl, but not 10s (error after about 3s).

I also tried to pass number of stored probes as 1 instead of default 32:

```python
with nengo_ocl.Simulator(model,n_prealloc_probes=1) as sim:
    sim.run(10.0)
```

but this didn't help - still the same error, perhaps even earlier in the simulation.

I'd appreciate any help.
Thanks!

PS: Should I write this here or on the nengo mailing list?

**Comment by tbekolay** [comment]
Hi @adityagilra! I think since it's an error running our included examples, I think here's good.

Could you check out the `update-220` branch and see if the example works there? It might be related to the example creating too many contexts, which should be better in the `update-220` branch. That branch also officially supports 2.2.0, so it's good to use anyhow.

PS: I edited your post to add in backticks (`) to render code snippets with an appropriate font. Hope that's ok!

**Comment by hunse** [comment]
Hi @adityagilra. What device are you running on? Is it a CPU or GPU? What type? Do you have another device you could test on?

I've found that these types of errors are often device-dependent.

**Comment by adityagilra** [comment]
Thanks @tbekolay and @hunse !

I tried the update-220 branch and I didn't need to fiddle with setup.py this time to install via
`python setup.py develop --user`

No warning about version incompatibility either, so I'm importing the right branch.

However, no luck with the error. Here it is -- it also shows my device -- an intel gpu on my laptop:

`~/nengo_ocl/examples$ python benchmark_circconv.py ocl 100
Choose platform:
[0] <pyopencl.Platform 'Intel Gen OCL Driver' at 0x7fc441758880>
Choice [0]:
Set the environment variable PYOPENCL_CTX='' to avoid being asked again.
No context argument was provided to nengo_ocl.Simulator
Calling pyopencl.create_some_context() for you now:
Choose platform:
[0] <pyopencl.Platform 'Intel Gen OCL Driver' at 0x7fc441758880>
Choice [0]:
Set the environment variable PYOPENCL_CTX='' to avoid being asked again.
/usr/local/lib/python2.7/dist-packages/pyopencl/__init__.py:207: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
Simulation finished in 0:00:01.                                                 
Simulation finished in 0:00:04.                                                 
OrderedDict([('benchmark', 'circ-conv'), ('name', 'Intel(R) HD Graphics 5500 BroadWell U-Processor GT2'), ('dim', 100), ('simtime', 1.0), ('neurons_per_product', 256), ('status', 'exception'), ('exception', 'clenqueuendrangekernel failed: OUT_OF_RESOURCES')])
Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, dims=100 exception
Traceback (most recent call last):
  File "benchmark_circconv.py", line 83, in <module>
    sim.run(simtime)
  File "/usr/local/lib/python2.7/dist-packages/nengo/simulator.py", line 261, in run
    self.run_steps(steps, progress_bar=progress_bar)
  File "/home/aditya/nengo_ocl/nengo_ocl/simulator.py", line 950, in run_steps
    self._plans.call_n_times(B)
  File "/home/aditya/nengo_ocl/nengo_ocl/plan.py", line 125, in call_n_times
    last_event = self.enqueue_n_times(n)
  File "/home/aditya/nengo_ocl/nengo_ocl/plan.py", line 138, in enqueue_n_times
    last_event = plan.enqueue(profiling=self.profiling)
  File "/home/aditya/nengo_ocl/nengo_ocl/plan.py", line 92, in enqueue
    wait_for=wait_for)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl/cffi_cl.py", line 1229, in enqueue_nd_range_kernel
    global_work_size, local_work_size, c_wait_for, num_wait_for))
  File "/usr/local/lib/python2.7/dist-packages/pyopencl/cffi_cl.py", line 561, in _handle_error
    raise e
pyopencl.cffi_cl.RuntimeError: clenqueuendrangekernel failed: OUT_OF_RESOURCES
`
------------

I've reserved a server with 2x NVidia Titan X GPU for tomorrow. So I'll report about that tomorrow.

Thanks!

PS: Also thanks for the backticks. Will use them from now on!

**Comment by hunse** [comment]
I've never tried running anything on an Intel GPU before. To tell you the truth, I'm guessing there's not much point in running on that device, since I doubt it will be any faster than just running on a CPU. Hopefully it works fine on the Titan. I've run Nengo OCL on those before.

However, it is strange that it runs for a while, but longer simulations make it crash. I'm not sure why that would be.

**Comment by adityagilra** [comment]
Actually, it was around 7x to 10x faster on the intel GPU Intel® HD Graphics 5500 (Broadwell GT2)  compared to the Intel® Core™ i7-5600U CPU @ 2.60GHz × 4 , at the sizes for which it ran. Am more hopeful on the NVidia Titan too. Will report tomorrow. Thanks!

**Comment by hunse** [comment]
I assume you were comparing to running with Nengo OCL on your CPU? A more fair comparison would be to compare to running Nengo with optimized BLAS ([I prefer OpenBLAS](https://hunseblog.wordpress.com/2014/09/15/installing-numpy-and-openblas/)). But you're right, it will depend a lot on your CPU.

**Comment by jgosmann** [comment]
> A more fair comparison would be to compare to running Nengo with optimized BLAS (I prefer OpenBLAS).

Are you sure? On my computer Nengo OCL (on the CPU) runs faster than the reference backend (even with an optimized BLAS). Using the nengo/nengo#1035 the differences will be smaller, but seems to be still there.

Nengo OCL can use all CPU cores, whereas the reference backend will only use one.

**Comment by hunse** [comment]
> Nengo OCL can use all CPU cores, whereas the reference backend will only use one.

So my impression was that that is BLAS dependent. I was going to tell you that my OpenBLAS install uses all cores. What I found is that it *can* use all cores. However, in a lot of our networks the operations are too small for it to actually do so. i.e. multiplying a 100 x 100 matrix with a vector will use all cores, but multiplying a 3 x 100 matrix with a vector only uses one core. So in practice, for many of our models, I think you're right: the reference backend is only using one core. (I may have also been mislead since many of my models have full connection weights, and so I think on my models the reference backend often makes use of all cores. But on standard Nengo models, it probably doesn't.)

I tried the `benchmark_circconv.py` example that comes with Nengo OCL, both on my home laptop and on my work computer. On my home laptop, I get the same result as you: OCL on the CPU is much faster than the reference simulator (roughly 3x faster). On my work computer, OCL on the CPU is slightly slower than the reference simulator (roughly 10% slower). I'm not sure why there would be this difference. I'm also surprised the difference goes that way, since I think my work computer is a better processor.

Anyway, it certainly doesn't seem to be the case that the reference backend with a good BLAS will be faster than nengo_ocl on the CPU. I was wrong about that!

**Comment by adityagilra** [comment]
I tried this on a server with 2x NVIDIA Titan X GPUs.

Both the current master branch and the update-220 branches run the benchmark_circonv.py example with the current nengo master branch 2.2.1.dev0 on Ubuntu 16.04. (The update-220 branch requires a newer pyopencl than the ubuntu official python-pyopencl, which can be obtained via pip.)

The example does not crash now, even for large number of dimensions. So I guess the previous crashes with the Intel GPU were either due to the driver or my installation...

`~/nengo_ocl/examples# python benchmark_circconv.py ref 100`

```
Simulation finished in 0:00:01.                                                 
Simulation finished in 0:01:08.                                                 
OrderedDict([('benchmark', 'circ-conv'), ('name', 'ref'), ('dim', 100), ('simtime', 1.0), ('neurons_per_product', 256), ('neurons', 129024), ('status', 'ok'), ('profiling', 0), ('buildtime', 4.300995111465454), ('warmtime', 0.45171189308166504), ('runtime', 67.71879315376282), ('rmse', 0.11634430199595876)])
ref, dims=100 successful
```

`python benchmark_circconv.py ocl 100`

```
/root/nengo_ocl/nengo_ocl/simulator.py:316: UserWarning: This version of `nengo_ocl` has not been tested with your `nengo` version (2.2.1.dev0). The latest fully supported version is 2.2.0
  nengo.__version__, latest_nengo_version))
No context argument was provided to nengo_ocl.Simulator
Calling pyopencl.create_some_context() for you now:
Simulation finished in 0:00:01.                                                 
Simulation finished in 0:00:01.                                                 
OrderedDict([('benchmark', 'circ-conv'), ('name', 'GeForce GTX TITAN X'), ('dim', 100), ('simtime', 1.0), ('neurons_per_product', 256), ('neurons', 129024), ('status', 'ok'), ('profiling', 0), ('buildtime', 7.593667030334473), ('warmtime', 0.011472940444946289), ('runtime', 0.6087701320648193), ('rmse', 0.11636551183952502)])
GeForce GTX TITAN X, dims=100 successful
```

The speedup is huge! Almost 50x per GPU for this example.

Thanks a lot guys for developing nengo_ocl! And for the help. I didn't try ocl on the CPU, but I guess as discussed above, the mileage varies...

I'll leave it to the developers to close this issue.
