### ISSUE TITLE
Raising errors for non-finite values

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_ocl#139]
In https://github.com/nengo/nengo/pull/1286 we explicitly raise an error is a direct-mode ensemble or node emits a non-finite value (nan or infinity). The tests added in that PR currently fail in Nengo OCL.

Would it be easy to raise the same error in OCL? Alternatively, since we're aiming for speed here, I think it would be justified to not raise an error, and instead just add those tests to the unsupported list, especially if supporting it would result in slowdowns.

Note that since this only affects tests, I don't consider it as a blocking issue for the Nengo 2.4.0 release.

**Comment by hunse** [comment]
This would be difficult to do in all cases (or would involve slowing the simulator down). We try to convert Python node functions to OCL code where possible. If they're converted, then we're never stopping in Python to look at the return value, and I don't know of any way to check this in OCL.

d98da19c2f3f324af2981361255b2663c3358c8f blacklists the corresponding tests, so everything passes again.
