### ISSUE TITLE
Add support for neuron noise

### ISSUE THREAD

**Issue by jaberg** [nengo/nengo_ocl#2]
Some models call for neurons to have some noise injected to their membrane potentials on every timestep.

The simplest thing to do is to call a special kernel for generating the random numbers, and add them to the bias on every timestep. Consider adding the random number generation into the LIF kernel itself.

PyOpenCL provides a RANLUX generator.

Look at how random numbers are generated by Theano's MRG generator, how they are generated by reika, and how they are generated by PyOpenCL's RANLUX implementation.

**Comment by hunse** [comment]
This is implemented via Processes now. Using PyOpenCL's generator, but there's also some stale code for using a Theano's generator that I implemented a while back (as of eae1ae53394b7843efb8483a4e71973e6d343289 in `nengo_ocl/clra_random.py`; I might get rid of it soon).
