### ISSUE TITLE
OCL on Mac not working

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_ocl#51]
In trying to use OCL on a mac, I got this.

RuntimeError: clBuildProgram failed: build program failure -

    Build on <pyopencl.Device 'Intel(R) Core(TM) i7-3720QM CPU @
    2.60GHz' on 'Apple' at 0xffffffff>:

    No kernels or only kernel prototypes found when build executable.
    (options: -I
    /Users/celiasmi/.virtualenvs/__ip/lib/python2.7/site-__packages/pyopencl/cl)
    (source saved as
    /var/folders/91/__dqhtq4ts7vd187fs23ctsg340000gn__/T/tmpLJbQLJ.cl)

    ERROR: An unexpected error occurred while tokenizing input
    The following traceback may be corrupted or invalid
    The error message is: ('EOF in multi-line string', (1, 8))

    Trevor suggested I run the test_sim_ocl script, which i did, and it
    failed (though it detected my cpu)...

    So then I went here:
    http://wiki.tiker.net/__PyOpenCL/Installation/Mac

    <http://wiki.tiker.net/PyOpenCL/Installation/Mac>

    And followed the steps at the bottom (for mac os x lion), and reran
    the tests and got the same thing. 

OS is Lion, 10.9

**Comment by jgosmann** [comment]
Same problem ... @jaberg seems to be correct.
