### ISSUE TITLE
Clyther for Direct, Node, PythonFunction

### ISSUE THREAD

**Issue by jaberg** [nengo/nengo_ocl#54]
@hunse Did you investigate Clyther for doing the ast_conversion type stuff?  What do you think of it?

http://srossross.github.io/Clyther/index.html

**Comment by hunse** [comment]
These nested functions are still a problem for AST conversion. Need to look into fixing them and/or taking out the nested functions in the Direct mode stuff in `nengo/builder/connection.py` for slicing inputs.

**Comment by hunse** [comment]
With nengo/nengo#729, we no longer use nested lambdas to do the slicing, so this is less of an issue. We may want to revisit this at some point, though, so that we can convert a wider range of node functions into OCL code.
