### ISSUE TITLE
SignalViews with sim_ocl

### ISSUE THREAD

**Issue by e2crawfo** [nengo/nengo_ocl#55]
So I'm trying to get learning to run on the GPU with nengo_ocl. Basically I've taken what @tbekolay did in ctn-waterloo/nengo#202 and made it do the same thing using signals and ops, so that we won't have to make any changes on the nengo_ocl side. What I have right now in nengo/builder.py is:

```python
    @builds(nengo.nonlinearities.PES)
    def build_pes(self, pes):
        activities = pes.connection.pre.neurons.output_signal
        error = pes.error_connection.output_signal
        scaled_error = Signal(np.zeros(error.shape))
        shaped_scaled_error = SignalView(scaled_error, (error.size, 1), (1,1), 0)
        shaped_activities = SignalView(activities, (1, activities.size), (1,1), 0)

        decoders = pes.connection.decoder_signal
        lr_signal = Signal(pes.learning_rate * 0.001)

        self.model.operators.append(
                Reset(scaled_error))
        self.model.operators.append(
                DotInc(lr_signal, error, scaled_error, tag="PES: scale error"))
        self.model.operators.append(
                ProdUpdate(shaped_scaled_error, shaped_activities, 
                           Signal(1), decoders, tag="PES: update"))
```

I'm using SignalViews there because the learning algorithm requires an outer product, and the error and activities signals are both 1-D arrays (their shape attr has length 1). This gives the same results as ctn-waterloo/nengo#202 with both the reference implementation and the nengo_ocl numpy simulator, but doesn't work with the ocl simulator. So two questions:

1. Does using a SignalView like this make sense, is that how they were meant to be used?
2. Anyone have any idea why it isn't working with the OCL simulator? Not really up to speed on how that thing works. Learning with OCL looks like this, if it helps at all:
![learning_with_ocl](https://f.cloud.github.com/assets/2119372/1895501/f478adc2-7b35-11e3-940b-3bd931cc2583.png)

**Comment by hunse** [comment]
PES now works in OCL, since we use the `ElementwiseInc` operator instead.
