### ISSUE TITLE
Model build time with nengo_ocl slower than with nengo

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo_ocl#61]
Building a model in nengo_ocl takes about 10-15x longer than with regular nengo. 
Here are some build times for differently sized models:

283950 neurons - nengo_ocl: 500s, nengo: 50s
488850 neurons - nengo_ocl: 1150s, nengo: 70s
892050 neurons - nengo_ocl: 3000s, nengo: 120s

Times were collected using a windows 8 machine with 2 x GTX660TI graphics cards, and an Intel i7-3770 3.40GHz quad-core processor.

**Comment by hunse** [comment]
This is much better now
