### ISSUE TITLE
Simple model has assert failure

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_ocl#68]
I just tried to run this model:

```python
import nengo
import numpy as np

model = nengo.Network()
with model:
    stim = nengo.Node(lambda t: np.sin(t*2))

    ens = nengo.Ensemble(100, 1)
    nengo.Connection(stim, ens)

    def output(t, x):
        print t, x
    out = nengo.Node(output, size_in=1)
    nengo.Connection(ens, out)

import nengo_ocl
sim = nengo_ocl.Simulator(model)
sim.run(1)
```

and I get this error:

```
Traceback (most recent call last):
  File ".\test.py", line 17, in <module>
    sim = nengo_ocl.Simulator(model)
  File "c:\users\terry\documents\github\nengo_ocl\nengo_ocl\sim_ocl.py", line 57, in __init__
    self, network=network, dt=dt, seed=seed, model=model)
  File "c:\users\terry\documents\github\nengo_ocl\nengo_ocl\sim_npy.py", line 456, in __init__
    op_groups = planner(operators)
  File "c:\users\terry\documents\github\nengo_ocl\nengo_ocl\sim_npy.py", line 282, in greedy_planner
    assert chosen
AssertionError
```

Am I doing something wrong?  It's been a while since I used ```nengo_ocl```.  Also, which version of nengo should I be using?  I went back to ```8dbe396``` since ```master``` doesn't work with ```nengo_ocl``` at the moment....

**Comment by tcstewar** [comment]
After a little bit of fiddling, is it just that ```nengo_ocl``` doesn't support output to Nodes?

**Comment by hunse** [comment]
You should be using Nengo v2.0.1. I'll look at this tomorrow.

**Comment by hunse** [comment]
No, it should support output to nodes I think.

**Comment by hunse** [comment]
It looks like the problem is with nodes that have no output. But it's fine if the output doesn't get used. So just add `return x` or `return 0` or something to the end of your function, and it should work.

**Comment by tcstewar** [comment]
> It looks like the problem is with nodes that have no output. But it's fine if the output doesn't get used. So just add return x or return 0 or something to the end of your function, and it should work.

Cool, I'll give that a try.  Unfortunately, that bug means that ```nengo_ocl``` doesn't work with ```nengo_gui```.  :(

**Comment by hunse** [comment]
Ahh, I see. In that case, I'll see if there's an easy fix.

**Comment by hunse** [comment]
@tcstewar: Give that fix a try.

**Comment by tcstewar** [comment]
Sweet!  That works.  Unfortunately, now I have a different and related bug:  A Node with no inputs and no outputs (i.e. a node that just gets called every time step with the current t)  doesn't work.  I'll post a separate issue for that.
