### ISSUE TITLE
Nodes with size_in==0 and size_out==0 fail

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_ocl#71]
It's a bit of a strange edge case, but I've often found it useful to have a Node with no inputs and no outputs to do some sort of timing operation.  In nengo_gui this is used to keep javascript up to date with what the current simulator time is.

This sort of Node seems to crash nengo_ocl:

```python
import nengo

model = nengo.Network()
with model:
    def timer(t):
        pass
    nengo.Node(timer, size_in=0, size_out=0)

import nengo_ocl
sim = nengo.Simulator(model)
sim.run(1)
```

**Comment by hunse** [comment]
Fixed!

**Comment by tcstewar** [comment]
Nice!  ```nengo_ocl``` now works with ```nengo_gui```!!!!  :) :)

**Comment by tcstewar** [comment]
(Note: if you want to try it out, you can select the backend from the options screen, or you can do it from the command line with ```--backend nengo_ocl```)
