### ISSUE TITLE
import nengo_ocl failed

### ISSUE THREAD

**Issue by MenelikV** [nengo/nengo_ocl#76]
Hello,

I wanted to use Nengo Ocl in a virtual envrionnement but importing the module failed.
Here is the error message I got in python shell:
>>> import nengo_ocl
:0: FutureWarning: IPython widgets are experimental and may change in the future.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_ocl/nengo_ocl/nengo_ocl/__init__.py", line 7, in <module>
    from .sim_ocl import Simulator
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_ocl/nengo_ocl/nengo_ocl/sim_ocl.py", line 11, in <module>
    from nengo.processes import StochasticProcess
ImportError: cannot import name StochasticProcess

Indeed in the last commit of Nengo, there is no class nor function in processes.py. 
Or did I do something wrong ?
Thanks for your help :)
Menelik

**Comment by jgosmann** [comment]
Which Nengo version do you have installed? I think, nengo_ocl requires 2.0.1 and won't work with the current master branch.

**Comment by MenelikV** [comment]
I have the current branch of Nengo

**Comment by jgosmann** [comment]
Yes, it is.

**Comment by MenelikV** [comment]
Thanks :)
